# Generated by Django 6.1.1 on 2026-09-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_cancelled_at_order_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
